plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.consumer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.consumer'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.pro.gold:progold-sdk:1.0.0'

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
}
